<a href="https://colab.research.google.com/github/adriana-rosales/Metodos-Numericos-2021-2/blob/main/Diferencias_Divididas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#GENERAL

**Aproximación de derivadas** cuando se tiene un **conjunto de datos**, en lugar de la forma analítica de f(x)


##Editar Listing:

*   5: `EDIT X`
*   6: `EDIT F(X),Y`

#1: x

A partir de los datos, elaborar una tabla de Diferencias Divididas.

\begin{array}{|c|c|c|c|}
\hline
x&1&5&20&40\\
\hline
f(x)&56.5&113&181&214.5\\
\hline
\end{array}


In [ ]:
import numpy as np
import matplotlib.pyplot as plt

x=np.array([1,5,20,40])                                #EDIT X
y=np.array([56.5,113,181,214.5])                       #EDIT F(x),Y               
n=x.size                                        

t=np.zeros((n,n))
t[:,0]=y

#Genera la tabla de Diferencias Divididas
for c in range(1,n):
    for r in range (0,n-c):
        t[r,c]=(t[r+1,c-1]-t[r,c-1]) / (x[r+c] - x[r])
print(t)

[[ 5.65000000e+01  1.41250000e+01 -5.04824561e-01  1.08502024e-02]
 [ 1.13000000e+02  4.53333333e+00 -8.16666667e-02  0.00000000e+00]
 [ 1.81000000e+02  1.67500000e+00  0.00000000e+00  0.00000000e+00]
 [ 2.14500000e+02  0.00000000e+00  0.00000000e+00  0.00000000e+00]]


#ORDINARIO B

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

x=np.array([1,2,3,5,7,8])                                #EDIT X
y=np.array([3,6,19,99,291,44])                       #EDIT F(x),Y               
n=x.size                                        

t=np.zeros((n,n))
t[:,0]=y

#Genera la tabla de Diferencias Divididas
for c in range(1,n):
    for r in range (0,n-c):
        t[r,c]=(t[r+1,c-1]-t[r,c-1]) / (x[r+c] - x[r])
print(t)

[[   3.            3.            5.            1.            0.
    -0.63492063]
 [   6.           13.            9.            1.           -4.44444444
     0.        ]
 [  19.           40.           14.          -25.66666667    0.
     0.        ]
 [  99.           96.         -114.33333333    0.            0.
     0.        ]
 [ 291.         -247.            0.            0.            0.
     0.        ]
 [  44.            0.            0.            0.            0.
     0.        ]]
