<a href="https://colab.research.google.com/github/adriana-rosales/Metodos-Numericos-2021-2/blob/main/Gauss_Jordan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**SOLUCIONADOR GAUSS-JORDAN:**

http://es.onlinemschool.com/math/assistance/equation/gaus/

#1: Libro **5x5**

In [ ]:
import numpy as np

def gaussJordan(a,b):
    n,_=np.shape(a)
    A=np.c_[a,b]
    for i in range(n):
        for j in range(n):
            # Si el término ya es cero continua con la siguiente
            if (A[j,i]!=0 and A[i,i]!=0 and i!=j):
                # Factor de reducción
                f=A[j,i]/A[i,i]
                A[j,i+1:n+1]=A[j,i+1:n+1]-f*A[i,i+1:n+1]
    # aplica la sustitución inversa
    x=np.zeros(n)
    for i in range(n):
        x[i]=A[i,n]/A[i,i]

    return x

def main():                                           #EDIT Matrix a,b
    a=np.array([[55.8,20.4,17.1,18.5,19.2],\
                [7.8,52.1,12.3,13.9,18.5],\
                [16.4,11.5,46.1,11.5,21.3],\
                [11.7,9.2,14.1,47.0,10.4],\
                [8.3,6.8,10.4,9.1,30.6]])
    b=np.array([2500,2000,2500,2000,1000])
    n,c=np.shape(a)
    r=np.linalg.matrix_rank(a)
    ab=np.c_[a,b]
    ra=np.linalg.matrix_rank(ab)

    print('rango(A)={} rango(Ab)={} n={}'.format(r,ra,n))

    if (r==ra==n):
        print('Solucion única=')
        x=gaussJordan(a,b)
        #x=np.linalg.solve(a,b)
        print(x)

    if (r==ra<n):
        print('Múltiples soluciones=')

    if (r<ra):
        print('Sin solución=')

if __name__ == "__main__": main()

# RESULTADO:

# Solución única= [17.65270678 19.67904691 35.15143662 22.69415361  4.82265608]

rango(A)=5 rango(Ab)=5 n=5
Solucion única=
[17.65270678 19.67904691 35.15143662 22.69415361  4.82265608]


#2: Ordinario A **3x3**

In [ ]:
import numpy as np

def gaussJordan(a,b):
    n,_=np.shape(a)
    A=np.c_[a,b]
    for i in range(n):
        for j in range(n):
            # Si el término ya es cero continua con la siguiente
            if (A[j,i]!=0 and A[i,i]!=0 and i!=j):
                # Factor de reducción
                f=A[j,i]/A[i,i]
                A[j,i+1:n+1]=A[j,i+1:n+1]-f*A[i,i+1:n+1]
    # aplica la sustitución inversa
    x=np.zeros(n)
    for i in range(n):
        x[i]=A[i,n]/A[i,i]

    return x

def main():                                        #EDIT Matrix a,b
    a=np.array([[0.876543,0.617341,0.589973],\
                [0.61231,0.784461,0.827742],\
                [0.317321,0.446779,0.476349]])
    b=np.array([0.863257,0.820647,0.450098])
    n,c=np.shape(a)
    r=np.linalg.matrix_rank(a)
    ab=np.c_[a,b]
    ra=np.linalg.matrix_rank(ab)

    print('rango(A)={} rango(Ab)={} n={}'.format(r,ra,n))

    if (r==ra==n):
        print('Solución única=')
        x=gaussJordan(a,b)
        #x=np.linalg.solve(a,b)
        print(x)

    if (r==ra<n):
        print('Múltiples soluciones=')

    if (r<ra):
        print('Sin solución=')

if __name__ == "__main__": main()

# RESULTADO:

# Solución única= [0.62822234 0.03174855 0.49662175]

rango(A)=3 rango(Ab)=3 n=3
Solución única=
[0.62822234 0.03174855 0.49662175]


#3: **3x3**

In [ ]:
import numpy as np

def gaussJordan(a,b):
    n,_=np.shape(a)
    A=np.c_[a,b]
    for i in range(n):
        for j in range(n):
            # Si el término ya es cero continua con la siguiente
            if (A[j,i]!=0 and A[i,i]!=0 and i!=j):
                # Factor de reducción
                f=A[j,i]/A[i,i]
                A[j,i+1:n+1]=A[j,i+1:n+1]-f*A[i,i+1:n+1]
    # aplica la sustitución inversa
    x=np.zeros(n)
    for i in range(n):
        x[i]=A[i,n]/A[i,i]

    return x

def main():                                           #EDIT Matrix a,b
    a=np.array([[1,-1,3],\
                [1,1,1],\
                [2,2,-1]])
    b=np.array([13,11,7])
    n,c=np.shape(a)
    r=np.linalg.matrix_rank(a)
    ab=np.c_[a,b]
    ra=np.linalg.matrix_rank(ab)

    print('rango(A)={} rango(Ab)={} n={}'.format(r,ra,n))

    if (r==ra==n):
        print('Solucion única=')
        x=gaussJordan(a,b)
        #x=np.linalg.solve(a,b)
        print(x)

    if (r==ra<n):
        print('Múltiples soluciones=')

    if (r<ra):
        print('Sin solución=')

if __name__ == "__main__": main()

# RESULTADO:

# Solución única= [2. 4. 5.]

rango(A)=3 rango(Ab)=3 n=3
Solucion única=
[2. 4. 5.]


#4: **4x4**

In [ ]:
import numpy as np

def gaussJordan(a,b):
    n,_=np.shape(a)
    A=np.c_[a,b]
    for i in range(n):
        for j in range(n):
            # Si el término ya es cero continua con la siguiente
            if (A[j,i]!=0 and A[i,i]!=0 and i!=j):
                # Factor de reducción
                f=A[j,i]/A[i,i]
                A[j,i+1:n+1]=A[j,i+1:n+1]-f*A[i,i+1:n+1]
    # aplica la sustitución inversa
    x=np.zeros(n)
    for i in range(n):
        x[i]=A[i,n]/A[i,i]

    return x

def main():                                        #EDIT Matrix a,b
    a=np.array([[1,-1,0,0],\
                [0,1,1,0],\
                [0,0,1,2],\
                [2,0,0,-3]])
    b=np.array([-6,3,4,5])
    n,c=np.shape(a)
    r=np.linalg.matrix_rank(a)
    ab=np.c_[a,b]
    ra=np.linalg.matrix_rank(ab)

    print('rango(A)={} rango(Ab)={} n={}'.format(r,ra,n))

    if (r==ra==n):
        print('Solución única=')
        x=gaussJordan(a,b)
        #x=np.linalg.solve(a,b)
        print(x)

    if (r==ra<n):
        print('Múltiples soluciones=')

    if (r<ra):
        print('Sin solución=')

if __name__ == "__main__": main()

# RESULTADO:

# Solución única= [ 31.  37. -34.  19.]

rango(A)=4 rango(Ab)=4 n=4
Solución única=
[ 31.  37. -34.  19.]


#5: **4x4** ❗️

In [ ]:
import numpy as np

def gaussJordan(a,b):
    n,_=np.shape(a)
    A=np.c_[a,b]
    for i in range(n):
        for j in range(n):
            # Si el término ya es cero continua con la siguiente
            if (A[j,i]!=0 and A[i,i]!=0 and i!=j):
                # Factor de reducción
                f=A[j,i]/A[i,i]
                A[j,i+1:n+1]=A[j,i+1:n+1]-f*A[i,i+1:n+1]
    # aplica la sustitución inversa
    x=np.zeros(n)
    for i in range(n):
        x[i]=A[i,n]/A[i,i]

    return x

def main():                                           #EDIT Matrix a,b
    a=np.array([[3,-1,1,2],\
                [-2,1,-1,-1],\
                [6,-3,2,5],\
                [4,2,3,0]])
    b=np.array([2,-1,4,1])
    n,c=np.shape(a)
    r=np.linalg.matrix_rank(a)
    ab=np.c_[a,b]
    ra=np.linalg.matrix_rank(ab)

    print('rango(A)={} rango(Ab)={} n={}'.format(r,ra,n))

    if (r==ra==n):
        print('Solucion única=')
        x=gaussJordan(a,b)
        #x=np.linalg.solve(a,b)
        print(x)

    if (r==ra<n):
        print('Múltiples soluciones=')

    if (r<ra):
        print('Sin solución=')

if __name__ == "__main__": main()

# RESULTADO MAL

# Solución CORRECTA(EXCEL)= [1  0 -1  0]

rango(A)=4 rango(Ab)=4 n=4
Solucion única=
[0.33333333        nan        nan 0.5       ]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:16: RuntimeWarning: invalid value encountered in long_scalars
  app.launch_new_instance()


#6: **4x4**

In [ ]:
import numpy as np

def gaussJordan(a,b):
    n,_=np.shape(a)
    A=np.c_[a,b]
    for i in range(n):
        for j in range(n):
            # Si el término ya es cero continua con la siguiente
            if (A[j,i]!=0 and A[i,i]!=0 and i!=j):
                # Factor de reducción
                f=A[j,i]/A[i,i]
                A[j,i+1:n+1]=A[j,i+1:n+1]-f*A[i,i+1:n+1]
    # aplica la sustitución inversa
    x=np.zeros(n)
    for i in range(n):
        x[i]=A[i,n]/A[i,i]

    return x

def main():                                           #EDIT Matrix a,b
    a=np.array([[0.07,0.18,0.15,0.24],\
                [0.03,0.25,0.1,0.65],\
                [0.55,0.41,0.55,0.09],\
                [0.35,0.16,0.2,0.02]])
    b=np.array([0.1,0.2,0.4,0.3])
    n,c=np.shape(a)
    r=np.linalg.matrix_rank(a)
    ab=np.c_[a,b]
    ra=np.linalg.matrix_rank(ab)

    print('rango(A)={} rango(Ab)={} n={}'.format(r,ra,n))

    if (r==ra==n):
        print('Solucion única=')
        x=gaussJordan(a,b)
        #x=np.linalg.solve(a,b)
        print(x)

    if (r==ra<n):
        print('Múltiples soluciones=')

    if (r<ra):
        print('Sin solución=')

if __name__ == "__main__": main()

# RESULTADO MAL

# Solución única= [1  0 -1  0]

rango(A)=4 rango(Ab)=4 n=4
Solucion única=
[ 1.00828729  0.50414365 -0.68508287  0.17265193]


#7: **4x4** ❗️

In [ ]:
import numpy as np

def gaussJordan(a,b):
    n,_=np.shape(a)
    A=np.c_[a,b]
    for i in range(n):
        for j in range(n):
            # Si el término ya es cero continua con la siguiente
            if (A[j,i]!=0 and A[i,i]!=0 and i!=j):
                # Factor de reducción
                f=A[j,i]/A[i,i]
                A[j,i+1:n+1]=A[j,i+1:n+1]-f*A[i,i+1:n+1]
    # aplica la sustitución inversa
    x=np.zeros(n)
    for i in range(n):
        x[i]=A[i,n]/A[i,i]

    return x

def main():                                           #EDIT Matrix a,b
    a=np.array([[16,6,4,1],\
                [1,-8,1,1],\
                [16,2,-4,1],\
                [9,8,-3,1]])
    b=np.array([-36,-64,-4,-64])
    n,c=np.shape(a)
    r=np.linalg.matrix_rank(a)
    ab=np.c_[a,b]
    ra=np.linalg.matrix_rank(ab)

    print('rango(A)={} rango(Ab)={} n={}'.format(r,ra,n))

    if (r==ra==n):
        print('Solucion única=')
        x=gaussJordan(a,b)
        #x=np.linalg.solve(a,b)
        print(x)

    if (r==ra<n):
        print('Múltiples soluciones=')

    if (r<ra):
        print('Sin solución=')

if __name__ == "__main__": main()

# RESULTADO MAL

# Solución CORRECTA (EXCEL)= [4  -4  -8  -92]

rango(A)=4 rango(Ab)=4 n=4
Solucion única=
[-3.125  7.625 -7.75    -inf]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:16: RuntimeWarning: divide by zero encountered in long_scalars
  app.launch_new_instance()


#8: **4x4** ❗️

In [ ]:
import numpy as np

def gaussJordan(a,b):
    n,_=np.shape(a)
    A=np.c_[a,b]
    for i in range(n):
        for j in range(n):
            # Si el término ya es cero continua con la siguiente
            if (A[j,i]!=0 and A[i,i]!=0 and i!=j):
                # Factor de reducción
                f=A[j,i]/A[i,i]
                A[j,i+1:n+1]=A[j,i+1:n+1]-f*A[i,i+1:n+1]
    # aplica la sustitución inversa
    x=np.zeros(n)
    for i in range(n):
        x[i]=A[i,n]/A[i,i]

    return x

def main():                                           #EDIT Matrix a,b
    a=np.array([[1,-2,2,-3],\
                [3,4,-1,1],\
                [2,-3,2,-1],\
                [1,1,-3,-2]])
    b=np.array([15,-6,17,-7])
    n,c=np.shape(a)
    r=np.linalg.matrix_rank(a)
    ab=np.c_[a,b]
    ra=np.linalg.matrix_rank(ab)

    print('rango(A)={} rango(Ab)={} n={}'.format(r,ra,n))

    if (r==ra==n):
        print('Solucion única=')
        x=gaussJordan(a,b)
        #x=np.linalg.solve(a,b)
        print(x)

    if (r==ra<n):
        print('Múltiples soluciones=')

    if (r<ra):
        print('Sin solución=')

if __name__ == "__main__": main()

# RESULTADO MAL

# Solución CORRECTA (EXCEL)= [2  -2  3 -1 ]

rango(A)=4 rango(Ab)=4 n=4
Solucion única=
[ 3.  -1.6  3.  -0.8]


#9: **4x4** ❗️

In [ ]:
import numpy as np

def gaussJordan(a,b):
    n,_=np.shape(a)
    A=np.c_[a,b]
    for i in range(n):
        for j in range(n):
            # Si el término ya es cero continua con la siguiente
            if (A[j,i]!=0 and A[i,i]!=0 and i!=j):
                # Factor de reducción
                f=A[j,i]/A[i,i]
                A[j,i+1:n+1]=A[j,i+1:n+1]-f*A[i,i+1:n+1]
    # aplica la sustitución inversa
    x=np.zeros(n)
    for i in range(n):
        x[i]=A[i,n]/A[i,i]

    return x

def main():                                           #EDIT Matrix a,b
    a=np.array([[1,2,-1,1],\
                [2,-1,2,3],\
                [-1,3,3,-2],\
                [3,-2,1,1]])
    b=np.array([0,7,17,-2])
    n,c=np.shape(a)
    r=np.linalg.matrix_rank(a)
    ab=np.c_[a,b]
    ra=np.linalg.matrix_rank(ab)

    print('rango(A)={} rango(Ab)={} n={}'.format(r,ra,n))

    if (r==ra==n):
        print('Solucion única=')
        x=gaussJordan(a,b)
        #x=np.linalg.solve(a,b)
        print(x)

    if (r==ra<n):
        print('Múltiples soluciones=')

    if (r<ra):
        print('Sin solución=')

if __name__ == "__main__": main()

# RESULTADO MAL

# Solución CORRECTA (EXCEL)= [-1  2 4 1]

rango(A)=4 rango(Ab)=4 n=4
Solucion única=
[0.         2.         4.         1.66666667]


#10: **3x3** ❗️



In [ ]:
import numpy as np

def gaussJordan(a,b):
    n,_=np.shape(a)
    A=np.c_[a,b]
    for i in range(n):
        for j in range(n):
            # Si el término ya es cero continua con la siguiente
            if (A[j,i]!=0 and A[i,i]!=0 and i!=j):
                # Factor de reducción
                f=A[j,i]/A[i,i]
                A[j,i+1:n+1]=A[j,i+1:n+1]-f*A[i,i+1:n+1]
    # aplica la sustitución inversa
    x=np.zeros(n)
    for i in range(n):
        x[i]=A[i,n]/A[i,i]

    return x

def main():                                           #EDIT Matrix a,b
    a=np.array([[2,3,1],\
                [3,-2,-4],\
                [5,-1,-1]])
    b=np.array([1,-3,4])
    n,c=np.shape(a)
    r=np.linalg.matrix_rank(a)
    ab=np.c_[a,b]
    ra=np.linalg.matrix_rank(ab)

    print('rango(A)={} rango(Ab)={} n={}'.format(r,ra,n))

    if (r==ra==n):
        print('Solucion única=')
        x=gaussJordan(a,b)
        #x=np.linalg.solve(a,b)
        print(x)

    if (r==ra<n):
        print('Múltiples soluciones=')

    if (r<ra):
        print('Sin solución=')

if __name__ == "__main__": main()

# RESULTADO MAL:

# Solución CORRECTA= [1  -1  2]

rango(A)=3 rango(Ab)=3 n=3
Solucion única=
[ 0.5 -1.   2. ]


#11: **3x3** 

In [ ]:
import numpy as np

def gaussJordan(a,b):
    n,_=np.shape(a)
    A=np.c_[a,b]
    for i in range(n):
        for j in range(n):
            # Si el término ya es cero continua con la siguiente
            if (A[j,i]!=0 and A[i,i]!=0 and i!=j):
                # Factor de reducción
                f=A[j,i]/A[i,i]
                A[j,i+1:n+1]=A[j,i+1:n+1]-f*A[i,i+1:n+1]
    # aplica la sustitución inversa
    x=np.zeros(n)
    for i in range(n):
        x[i]=A[i,n]/A[i,i]

    return x

def main():                                           #EDIT Matrix a,b
    a=np.array([[3,2,4],\
                [5,-1,-3],\
                [4,3,1]])
    b=np.array([1,-7,2])
    n,c=np.shape(a)
    r=np.linalg.matrix_rank(a)
    ab=np.c_[a,b]
    ra=np.linalg.matrix_rank(ab)

    print('rango(A)={} rango(Ab)={} n={}'.format(r,ra,n))

    if (r==ra==n):
        print('Solucion única=')
        x=gaussJordan(a,b)
        #x=np.linalg.solve(a,b)
        print(x)

    if (r==ra<n):
        print('Múltiples soluciones=')

    if (r<ra):
        print('Sin solución=')

if __name__ == "__main__": main()

# RESULTADO:

# Solución única= [-1.  2. -0.]

rango(A)=3 rango(Ab)=3 n=3
Solucion única=
[-1.  2. -0.]
